version: "3.9"

services:
  db:
    image: postgres
    ports: [5432:5432]
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DB_HOST: db
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - api

networks:
  api:
