version: '3.9'

services:
  testdb:
    image: postgres
    ports:
      - '5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  testrunner:
    build:
      context: ./
      dockerfile: Dockerfile.test
    depends_on:
      - testdb
    ports:
      - '5000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_HOST: testdb
networks:
  testapi: